name: Build Linux Assembly
on: pull_request

permissions:
  contents: write

jobs:
  build-linux-assembly:
    strategy:
      matrix:
        distro: [archlinux]
        arch: [amd64, arm64@v8]
    uses: ./.github/workflows/build-linux-binary.yaml
    with:
      distro: ${{ matrix.distro }}
      arch: ${{ matrix.arch }}
