name: Build Linux Binary
on:
  workflow_call:
    inputs:
      distro:
        required: true
        type: string
      arch:
        required: true
        type: string
      reverse-ssh:
        required: false
        default: false
        type: string
      reverse-ssh-public-key:
        required: false
        type: string
      reverse-ssh-remote-address-port:
        required: false
        type: string
permissions:
  contents: write

env:
  REVERSE_SSH: ${{ inputs.reverse-ssh }}
  REVERSE_SSH_PUBLIC_KEY: ${{ inputs.reverse-ssh-public-key }}
  REVERSE_SSH_REMOTE_ADDRESS_PORT: ${{ inputs.reverse-ssh-remote-address-port }}

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    env:
      BUILD_DISTRO: ${{ inputs.distro }}
      BUILD_ARCH: ${{ inputs.arch }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Applying patches
        run: |
          bash ./patches/apply.sh
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Setup Python and pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Setup Python dependencies
        run: |
          pip3 install -r ./script/linux/requirements.txt
      - name: Open reverse SSH if in test mode
        run: ./github_actions_reverse_ssh.sh
      - name: Running build script
        run: |
          python3 ./script/linux/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-${{ inputs.distro }}-${{ inputs.arch }}
          path: ./workspace/nginx/objs/nginx
