name: Release Docker Image
on:
  workflow_call:
    inputs:
      run_id:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wxx9248/nginx

permissions:
  packages: write

jobs:
  release-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v5
        with:
          run_id: ${{ inputs.run_id }}
          path: ./docker

      - name: Docker Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to the Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.1.0
        with:
          context: ./docker
          push: true
          platforms: >
              linux/amd64,
              linux/386,
              linux/arm64,
              linux/arm/v6,linux/arm/v7,
              linux/ppc64le
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
