name: Release
on:
  workflow_dispatch:
    inputs:
      run_id_docker:
        description: GitHub Actions Run ID for Releasing Docker Image
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  release-docker-image:
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/release-docker-image.yaml
    with:
      run_id: ${{ inputs.run_id_docker }}
