name: Release Docker Image
on:
  workflow_call:
    inputs:
      run_id:
        required: true
        type: string

permissions:
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        run: |
          echo Hello world!
